#!/bin/bash

set -e

readonly DEFAULT_INSTALL_PATH="/opt/consul-template"
readonly DEFAULT_CONSUL_TEMPLATE_USER="consul-template"

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SYSTEM_BIN_DIR="/usr/local/bin"

readonly SUPERVISOR_DIR="/etc/supervisor"
readonly SUPERVISOR_CONF_DIR="$SUPERVISOR_DIR/conf.d"

readonly SCRIPT_NAME="$(basename "$0")"

function log {
  local readonly level="$1"
  local readonly message="$2"
  local readonly timestamp=$(date +"%Y-%m-%d %H:%M:%S")
  >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
}

function log_info {
  local readonly message="$1"
  log "INFO" "$message"
}

function log_warn {
  local readonly message="$1"
  log "WARN" "$message"
}

function log_error {
  local readonly message="$1"
  log "ERROR" "$message"
}

function assert_not_empty {
  local readonly arg_name="$1"
  local readonly arg_value="$2"

  if [[ -z "$arg_value" ]]; then
    log_error "The value for '$arg_name' cannot be empty"
    print_usage
    exit 1
  fi
}

function has_yum {
  [ -n "$(command -v yum)" ]
}

function has_apt_get {
  [ -n "$(command -v apt-get)" ]
}

function user_exists {
  local readonly username="$1"
  id "$username" >/dev/null 2>&1
}

function create_consul_template_user {
  local readonly username="$1"

  if $(user_exists "$username"); then
    echo "User $username already exists. Will not create again."
  else
    log_info "Creating user named $username"
    sudo useradd "$username"
  fi
}

function create_consul_template_install_paths {
  local readonly path="$1"
  local readonly username="$2"

  log_info "Creating install dirs for Consul Template at $path"
  sudo mkdir -p "$path"
  sudo mkdir -p "$path/bin"
  sudo mkdir -p "$path/config"
  sudo mkdir -p "$path/data"

  log_info "Changing ownership of $path to $username"
  sudo chown -R "$username:$username" "$path"
}

function install_binaries {
  local readonly version="$1"
  local readonly path="$2"
  local readonly username="$3"

  local readonly url="https://releases.hashicorp.com/consul-template/${version}/consul-template_${version}_linux_amd64.zip"
  local readonly download_path="/tmp/consul-template_${version}_linux_amd64.zip"
  local readonly bin_dir="$path/bin"
  local readonly consul_template_dest_path="$bin_dir/consul-template"
  local readonly run_consul_template_dest_path="$bin_dir/run-consul-template"

  log_info "Downloading Consul Template $version from $url to $download_path"
  curl -o "$download_path" "$url"
  unzip -d /tmp "$download_path"

  log_info "Moving Consul Template binary to $consul_template_dest_path"
  sudo mv "/tmp/consul-template" "$consul_template_dest_path"
  sudo chown "$username:$username" "$consul_template_dest_path"
  sudo chmod a+x "$consul_template_dest_path"

  local readonly symlink_path="$SYSTEM_BIN_DIR/consul-template"
  if [[ -f "$symlink_path" ]]; then
    log_info "Symlink $symlink_path already exists. Will not add again."
  else
    log_info "Adding symlink to $consul_template_dest_path in $symlink_path"
    sudo ln -s "$consul_template_dest_path" "$symlink_path"
  fi

  log_info "Copying Consul Template run script to $run_consul_template_dest_path"
  sudo cp "$SCRIPT_DIR/../run-consul-template/run-consul-template" "$run_consul_template_dest_path"
  sudo chown "$username:$username" "$run_consul_template_dest_path"
  sudo chmod a+x "$run_consul_template_dest_path"
}

function install {
  local version=""
  local path="$DEFAULT_INSTALL_PATH"
  local user="$DEFAULT_CONSUL_TEMPLATE_USER"

  log_info "Local vars"
  
  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
      --version)
        version="$2"
        shift
        ;;
      --path)
        path="$2"
        shift
        ;;
      --user)
        user="$2"
        shift
        ;;
      --help)
        print_usage
        exit
        ;;
      *)
        log_error "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

  assert_not_empty "--version" "$version"
  assert_not_empty "--path" "$path"
  assert_not_empty "--user" "$user"

  log_info "Starting Consul Template install"

  create_consul_template_user "$user"
  create_consul_template_install_paths "$path" "$user"
  install_binaries "$version" "$path" "$user"

  log_info "Consul Template install complete!"
}

install "$@"
